// Generated by scripts/generate-db-types.mjs from supabase/migrations. Do not edit by hand.
// Regenerate with: npm run db:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      admin_users: {
        Row: {
          created_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      lead_rate_limits: {
        Row: {
          bucket: string;
          created_at: string;
        };
        Insert: {
          bucket: string;
          created_at?: string;
        };
        Update: {
          bucket?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          consent: boolean;
          created_at: string;
          email: string | null;
          fbclid: string | null;
          form_name: string;
          gbraid: string | null;
          gclid: string | null;
          id: string;
          is_test: boolean;
          landing_page: string | null;
          message: string | null;
          name: string;
          notification_error: string | null;
          notification_status: string;
          notified_at: string | null;
          phone: string;
          project_type: string | null;
          referrer: string | null;
          status: string;
          submission_id: string | null;
          ttclid: string | null;
          updated_at: string;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_medium: string | null;
          utm_source: string | null;
          utm_term: string | null;
          wbraid: string | null;
        };
        Insert: {
          consent?: boolean;
          created_at?: string;
          email?: string | null;
          fbclid?: string | null;
          form_name: string;
          gbraid?: string | null;
          gclid?: string | null;
          id?: string;
          is_test?: boolean;
          landing_page?: string | null;
          message?: string | null;
          name: string;
          notification_error?: string | null;
          notification_status?: string;
          notified_at?: string | null;
          phone: string;
          project_type?: string | null;
          referrer?: string | null;
          status?: string;
          submission_id?: string | null;
          ttclid?: string | null;
          updated_at?: string;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_medium?: string | null;
          utm_source?: string | null;
          utm_term?: string | null;
          wbraid?: string | null;
        };
        Update: {
          consent?: boolean;
          created_at?: string;
          email?: string | null;
          fbclid?: string | null;
          form_name?: string;
          gbraid?: string | null;
          gclid?: string | null;
          id?: string;
          is_test?: boolean;
          landing_page?: string | null;
          message?: string | null;
          name?: string;
          notification_error?: string | null;
          notification_status?: string;
          notified_at?: string | null;
          phone?: string;
          project_type?: string | null;
          referrer?: string | null;
          status?: string;
          submission_id?: string | null;
          ttclid?: string | null;
          updated_at?: string;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_medium?: string | null;
          utm_source?: string | null;
          utm_term?: string | null;
          wbraid?: string | null;
        };
        Relationships: [];
      };
      page_seo: {
        Row: {
          canonical_url: string | null;
          meta_description: string | null;
          meta_title: string | null;
          og_description: string | null;
          og_image_url: string | null;
          og_title: string | null;
          path: string;
          robots_follow: boolean;
          robots_index: boolean;
          updated_at: string;
        };
        Insert: {
          canonical_url?: string | null;
          meta_description?: string | null;
          meta_title?: string | null;
          og_description?: string | null;
          og_image_url?: string | null;
          og_title?: string | null;
          path: string;
          robots_follow?: boolean;
          robots_index?: boolean;
          updated_at?: string;
        };
        Update: {
          canonical_url?: string | null;
          meta_description?: string | null;
          meta_title?: string | null;
          og_description?: string | null;
          og_image_url?: string | null;
          og_title?: string | null;
          path?: string;
          robots_follow?: boolean;
          robots_index?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      posts: {
        Row: {
          author: string | null;
          canonical_url: string | null;
          category: string | null;
          content: Json;
          created_at: string;
          excerpt: string | null;
          featured_image_alt: string | null;
          featured_image_url: string | null;
          id: string;
          meta_description: string | null;
          meta_title: string | null;
          og_image_url: string | null;
          published_at: string | null;
          robots_index: boolean;
          slug: string;
          status: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          author?: string | null;
          canonical_url?: string | null;
          category?: string | null;
          content?: Json;
          created_at?: string;
          excerpt?: string | null;
          featured_image_alt?: string | null;
          featured_image_url?: string | null;
          id?: string;
          meta_description?: string | null;
          meta_title?: string | null;
          og_image_url?: string | null;
          published_at?: string | null;
          robots_index?: boolean;
          slug: string;
          status?: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          author?: string | null;
          canonical_url?: string | null;
          category?: string | null;
          content?: Json;
          created_at?: string;
          excerpt?: string | null;
          featured_image_alt?: string | null;
          featured_image_url?: string | null;
          id?: string;
          meta_description?: string | null;
          meta_title?: string | null;
          og_image_url?: string | null;
          published_at?: string | null;
          robots_index?: boolean;
          slug?: string;
          status?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      redirects: {
        Row: {
          active: boolean;
          created_at: string;
          destination: string;
          id: string;
          source_path: string;
          status_code: number;
          updated_at: string;
        };
        Insert: {
          active?: boolean;
          created_at?: string;
          destination: string;
          id?: string;
          source_path: string;
          status_code?: number;
          updated_at?: string;
        };
        Update: {
          active?: boolean;
          created_at?: string;
          destination?: string;
          id?: string;
          source_path?: string;
          status_code?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      site_settings: {
        Row: {
          address: string | null;
          business_name: string | null;
          consent_default: string;
          default_meta_description: string | null;
          default_meta_title: string | null;
          default_og_image_url: string | null;
          email: string | null;
          facebook_url: string | null;
          favicon_url: string | null;
          ga4_id: string | null;
          gtm_id: string | null;
          id: number;
          indexing_enabled: boolean;
          instagram_url: string | null;
          linkedin_partner_id: string | null;
          linkedin_url: string | null;
          local_business_schema_enabled: boolean;
          logo_url: string | null;
          meta_pixel_id: string | null;
          phone: string | null;
          site_name: string | null;
          site_url: string | null;
          tiktok_pixel_id: string | null;
          tiktok_url: string | null;
          updated_at: string;
          whatsapp: string | null;
          youtube_url: string | null;
        };
        Insert: {
          address?: string | null;
          business_name?: string | null;
          consent_default?: string;
          default_meta_description?: string | null;
          default_meta_title?: string | null;
          default_og_image_url?: string | null;
          email?: string | null;
          facebook_url?: string | null;
          favicon_url?: string | null;
          ga4_id?: string | null;
          gtm_id?: string | null;
          id?: number;
          indexing_enabled?: boolean;
          instagram_url?: string | null;
          linkedin_partner_id?: string | null;
          linkedin_url?: string | null;
          local_business_schema_enabled?: boolean;
          logo_url?: string | null;
          meta_pixel_id?: string | null;
          phone?: string | null;
          site_name?: string | null;
          site_url?: string | null;
          tiktok_pixel_id?: string | null;
          tiktok_url?: string | null;
          updated_at?: string;
          whatsapp?: string | null;
          youtube_url?: string | null;
        };
        Update: {
          address?: string | null;
          business_name?: string | null;
          consent_default?: string;
          default_meta_description?: string | null;
          default_meta_title?: string | null;
          default_og_image_url?: string | null;
          email?: string | null;
          facebook_url?: string | null;
          favicon_url?: string | null;
          ga4_id?: string | null;
          gtm_id?: string | null;
          id?: number;
          indexing_enabled?: boolean;
          instagram_url?: string | null;
          linkedin_partner_id?: string | null;
          linkedin_url?: string | null;
          local_business_schema_enabled?: boolean;
          logo_url?: string | null;
          meta_pixel_id?: string | null;
          phone?: string | null;
          site_name?: string | null;
          site_url?: string | null;
          tiktok_pixel_id?: string | null;
          tiktok_url?: string | null;
          updated_at?: string;
          whatsapp?: string | null;
          youtube_url?: string | null;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      is_admin: { Args: never; Returns: boolean };
      lead_rate_limit_consume: { Args: { p_bucket: string; p_limit: number; p_window_seconds: number }; Returns: boolean };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
