-- GENERATED by scripts/build-install-sql.mjs from supabase/migrations. Do not edit; run `npm run db:install-sql`.
-- Fresh Lookup Starter install: paste into Supabase → SQL Editor of a NEW project and run once.
-- Runs every migration in one transaction: either everything is created or nothing is.
-- For an EXISTING project, apply only the missing files from supabase/migrations instead.

begin;

-- ═══ 20260915130000_lookup_foundation.sql ═══
-- Lookup website infrastructure — 1/4: foundation (admin allowlist, helper functions).
-- Additive only. Aborts WITHOUT changing anything if any Lookup object already exists.

do $$
declare
  existing_tables text;
begin
  select string_agg(table_name, ', ')
    into existing_tables
    from information_schema.tables
   where table_schema = 'public'
     and table_name in ('admin_users', 'site_settings', 'page_seo', 'posts', 'leads', 'redirects');

  if existing_tables is not null then
    raise exception 'Lookup migration aborted: public tables already exist: %. Nothing was changed.', existing_tables;
  end if;

  if exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname in ('is_admin', 'set_updated_at')
  ) then
    raise exception 'Lookup migration aborted: public.is_admin() or public.set_updated_at() already exists. Nothing was changed.';
  end if;
end
$$;

-- Admin allowlist: a signed-in Supabase Auth user is an admin only if listed here.
create table public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

comment on table public.admin_users is 'Lookup: users allowed into /admin. Add rows via SQL only.';

alter table public.admin_users enable row level security;

create policy "admin_users: read own row"
  on public.admin_users for select
  to authenticated
  using (user_id = (select auth.uid()));

revoke all on public.admin_users from anon, authenticated;
grant select on public.admin_users to authenticated;
grant all on public.admin_users to service_role;

-- True when the current request belongs to an allowlisted admin. Used by RLS policies.
create function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (select 1 from public.admin_users where user_id = (select auth.uid()));
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated, service_role;

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ═══ 20260915130100_lookup_content.sql ═══
-- Lookup website infrastructure — 2/4: content (site settings, page SEO, blog posts, redirects).
-- Additive only. Public reads are limited by RLS; every write requires public.is_admin().

-- Site settings (single row, id = 1) ----------------------------------------------------------
create table public.site_settings (
  id smallint primary key default 1 constraint site_settings_singleton check (id = 1),
  business_name text check (char_length(business_name) <= 200),
  site_name text check (char_length(site_name) <= 200),
  site_url text check (site_url ~ '^https?://' and char_length(site_url) <= 300),
  phone text check (char_length(phone) <= 40),
  whatsapp text check (whatsapp ~ '^[0-9+ -]{6,25}$'),
  email text check (char_length(email) <= 200),
  address text check (char_length(address) <= 300),
  logo_url text check (char_length(logo_url) <= 1000),
  favicon_url text check (char_length(favicon_url) <= 1000),
  facebook_url text check (facebook_url ~ '^https://'),
  instagram_url text check (instagram_url ~ '^https://'),
  linkedin_url text check (linkedin_url ~ '^https://'),
  tiktok_url text check (tiktok_url ~ '^https://'),
  youtube_url text check (youtube_url ~ '^https://'),
  default_meta_title text check (char_length(default_meta_title) <= 200),
  default_meta_description text check (char_length(default_meta_description) <= 500),
  default_og_image_url text check (char_length(default_og_image_url) <= 1000),
  indexing_enabled boolean not null default false,
  local_business_schema_enabled boolean not null default false,
  gtm_id text check (gtm_id ~ '^GTM-[A-Z0-9]{4,12}$'),
  ga4_id text check (ga4_id ~ '^G-[A-Z0-9]{4,20}$'),
  meta_pixel_id text check (meta_pixel_id ~ '^[0-9]{5,20}$'),
  tiktok_pixel_id text check (tiktok_pixel_id ~ '^[A-Za-z0-9]{5,40}$'),
  linkedin_partner_id text check (linkedin_partner_id ~ '^[0-9]{3,15}$'),
  updated_at timestamptz not null default now()
);

comment on table public.site_settings is 'Lookup: global site settings. Public IDs only — never store secrets here.';

-- Empty values fall back to the defaults in code. Indexing starts disabled.
insert into public.site_settings (id) values (1);

create trigger site_settings_set_updated_at
  before update on public.site_settings
  for each row execute function public.set_updated_at();

alter table public.site_settings enable row level security;

create policy "site_settings: public read"
  on public.site_settings for select to anon, authenticated using (true);
create policy "site_settings: admin update"
  on public.site_settings for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

revoke all on public.site_settings from anon, authenticated;
grant select on public.site_settings to anon, authenticated;
grant update on public.site_settings to authenticated;
grant all on public.site_settings to service_role;

-- Page SEO (per static route) ------------------------------------------------------------------
create table public.page_seo (
  path text primary key check (path ~ '^/' and char_length(path) <= 300),
  meta_title text check (char_length(meta_title) <= 200),
  meta_description text check (char_length(meta_description) <= 500),
  canonical_url text check (canonical_url ~ '^https?://' and char_length(canonical_url) <= 1000),
  og_title text check (char_length(og_title) <= 200),
  og_description text check (char_length(og_description) <= 500),
  og_image_url text check (char_length(og_image_url) <= 1000),
  robots_index boolean not null default true,
  robots_follow boolean not null default true,
  updated_at timestamptz not null default now()
);

create trigger page_seo_set_updated_at
  before update on public.page_seo
  for each row execute function public.set_updated_at();

alter table public.page_seo enable row level security;

create policy "page_seo: public read"
  on public.page_seo for select to anon, authenticated using (true);
create policy "page_seo: admin insert"
  on public.page_seo for insert to authenticated with check ((select public.is_admin()));
create policy "page_seo: admin update"
  on public.page_seo for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "page_seo: admin delete"
  on public.page_seo for delete to authenticated using ((select public.is_admin()));

revoke all on public.page_seo from anon, authenticated;
grant select on public.page_seo to anon, authenticated;
grant insert, update, delete on public.page_seo to authenticated;
grant all on public.page_seo to service_role;

-- Blog posts ------------------------------------------------------------------------------------
create table public.posts (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 200),
  slug text not null unique
    check (slug ~ '^[a-z0-9א-ת]+(-[a-z0-9א-ת]+)*$' and char_length(slug) <= 120),
  excerpt text check (char_length(excerpt) <= 500),
  content jsonb not null default '{"type":"doc","content":[]}'::jsonb,
  featured_image_url text check (char_length(featured_image_url) <= 1000),
  featured_image_alt text check (char_length(featured_image_alt) <= 200),
  category text check (char_length(category) <= 80),
  author text check (char_length(author) <= 120),
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  meta_title text check (char_length(meta_title) <= 200),
  meta_description text check (char_length(meta_description) <= 500),
  canonical_url text check (canonical_url ~ '^https?://' and char_length(canonical_url) <= 1000),
  og_image_url text check (char_length(og_image_url) <= 1000),
  robots_index boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint posts_published_requires_date check (status = 'draft' or published_at is not null)
);

create index posts_status_published_at_idx on public.posts (status, published_at desc);

create trigger posts_set_updated_at
  before update on public.posts
  for each row execute function public.set_updated_at();

alter table public.posts enable row level security;

create policy "posts: public read published"
  on public.posts for select to anon, authenticated
  using (status = 'published' and published_at <= now());
create policy "posts: admin read all"
  on public.posts for select to authenticated using ((select public.is_admin()));
create policy "posts: admin insert"
  on public.posts for insert to authenticated with check ((select public.is_admin()));
create policy "posts: admin update"
  on public.posts for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "posts: admin delete"
  on public.posts for delete to authenticated using ((select public.is_admin()));

revoke all on public.posts from anon, authenticated;
grant select on public.posts to anon, authenticated;
grant insert, update, delete on public.posts to authenticated;
grant all on public.posts to service_role;

-- Redirects -------------------------------------------------------------------------------------
create table public.redirects (
  id uuid primary key default gen_random_uuid(),
  source_path text not null unique check (source_path ~ '^/' and char_length(source_path) <= 500),
  destination text not null
    check ((destination ~ '^/' or destination ~ '^https?://') and char_length(destination) <= 1000),
  status_code smallint not null default 301 check (status_code in (301, 302)),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint redirects_not_self check (source_path <> destination)
);

create trigger redirects_set_updated_at
  before update on public.redirects
  for each row execute function public.set_updated_at();

alter table public.redirects enable row level security;

create policy "redirects: public read active"
  on public.redirects for select to anon, authenticated using (active);
create policy "redirects: admin read all"
  on public.redirects for select to authenticated using ((select public.is_admin()));
create policy "redirects: admin insert"
  on public.redirects for insert to authenticated with check ((select public.is_admin()));
create policy "redirects: admin update"
  on public.redirects for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "redirects: admin delete"
  on public.redirects for delete to authenticated using ((select public.is_admin()));

revoke all on public.redirects from anon, authenticated;
grant select on public.redirects to anon, authenticated;
grant insert, update, delete on public.redirects to authenticated;
grant all on public.redirects to service_role;

-- ═══ 20260915130200_lookup_leads.sql ═══
-- Lookup website infrastructure — 3/4: leads.
-- Contains personal data. No public access at all: inserts happen only on the server with the service role
-- key (which bypasses RLS); only allowlisted admins can read.

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 200),
  phone text not null check (char_length(phone) between 1 and 40),
  email text check (char_length(email) <= 200),
  message text check (char_length(message) <= 5000),
  project_type text check (char_length(project_type) <= 100),
  consent boolean not null default false,
  form_name text not null check (char_length(form_name) between 1 and 60),
  landing_page text check (char_length(landing_page) <= 1000),
  referrer text check (char_length(referrer) <= 1000),
  utm_source text check (char_length(utm_source) <= 255),
  utm_medium text check (char_length(utm_medium) <= 255),
  utm_campaign text check (char_length(utm_campaign) <= 255),
  utm_content text check (char_length(utm_content) <= 255),
  utm_term text check (char_length(utm_term) <= 255),
  gclid text check (char_length(gclid) <= 255),
  gbraid text check (char_length(gbraid) <= 255),
  wbraid text check (char_length(wbraid) <= 255),
  fbclid text check (char_length(fbclid) <= 255),
  ttclid text check (char_length(ttclid) <= 255),
  -- Generated once per form view; makes retried submissions idempotent.
  submission_id uuid unique
);

comment on table public.leads is 'Lookup: website leads (PII). Insert via server-side service role only; admins read.';

create index leads_created_at_idx on public.leads (created_at desc);

alter table public.leads enable row level security;

create policy "leads: admin read"
  on public.leads for select to authenticated using ((select public.is_admin()));

revoke all on public.leads from anon, authenticated;
grant select on public.leads to authenticated;
grant all on public.leads to service_role;

-- ═══ 20260915130300_lookup_media_storage.sql ═══
-- Lookup website infrastructure — 4/4: media storage.
-- Public-read bucket for site images (featured images, OG images, logo, favicon, content images).
-- Uploads limited to 5 MB raster images (no SVG — it can carry scripts). Only admins can write.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media',
  'media',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/gif', 'image/x-icon', 'image/vnd.microsoft.icon']
);

create policy "media: admin read"
  on storage.objects for select to authenticated
  using (bucket_id = 'media' and (select public.is_admin()));
create policy "media: admin upload"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'media' and (select public.is_admin()));
create policy "media: admin update"
  on storage.objects for update to authenticated
  using (bucket_id = 'media' and (select public.is_admin()))
  with check (bucket_id = 'media' and (select public.is_admin()));
create policy "media: admin delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'media' and (select public.is_admin()));

-- ═══ 20260916090000_lookup_hardening.sql ═══
-- Lookup website infrastructure — 5: hardening.
-- Lead workflow (status, test flag, notification delivery state, admin update/delete), anti-spam rate limiting,
-- and the Consent Mode default. Additive only. Aborts WITHOUT changing anything if run before 1–4 or run twice.

do $$
begin
  if to_regclass('public.leads') is null or to_regclass('public.site_settings') is null then
    raise exception 'Lookup hardening migration aborted: apply migrations 1-4 first. Nothing was changed.';
  end if;

  if exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'leads' and column_name in ('status', 'is_test', 'notification_status')
  ) or to_regclass('public.lead_rate_limits') is not null then
    raise exception 'Lookup hardening migration aborted: it is already applied. Nothing was changed.';
  end if;
end
$$;

-- Leads: workflow status, test marker, notification delivery state ---------------------------------
alter table public.leads
  add column status text not null default 'new'
    constraint leads_status_check check (status in ('new', 'contacted', 'closed', 'spam')),
  add column is_test boolean not null default false,
  add column notification_status text not null default 'skipped'
    constraint leads_notification_status_check check (notification_status in ('pending', 'sent', 'failed', 'skipped')),
  add column notification_error text check (char_length(notification_error) <= 500),
  add column notified_at timestamptz,
  add column updated_at timestamptz not null default now();

comment on column public.leads.is_test is 'Automated test submissions (E2E). Hidden from admin lists, exports and notifications.';

create index leads_status_created_at_idx on public.leads (status, created_at desc) where not is_test;

create trigger leads_set_updated_at
  before update on public.leads
  for each row execute function public.set_updated_at();

create policy "leads: admin update status"
  on public.leads for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "leads: admin delete"
  on public.leads for delete to authenticated
  using ((select public.is_admin()));

-- Admins may change only the workflow status; submitted data and attribution stay immutable.
grant update (status) on public.leads to authenticated;
grant delete on public.leads to authenticated;

-- Anti-spam: per-client rate limiting (called only by the server with the service role) ---------------
create table public.lead_rate_limits (
  bucket text not null check (char_length(bucket) between 1 and 128),
  created_at timestamptz not null default now()
);

comment on table public.lead_rate_limits is 'Lookup: lead submission rate-limit events keyed by a hashed client identifier. No personal data.';

create index lead_rate_limits_bucket_created_at_idx on public.lead_rate_limits (bucket, created_at desc);
create index lead_rate_limits_created_at_idx on public.lead_rate_limits (created_at);

alter table public.lead_rate_limits enable row level security;
revoke all on public.lead_rate_limits from anon, authenticated;
grant all on public.lead_rate_limits to service_role;

-- Records one submission attempt for the bucket and returns true when it is within the limit.
create function public.lead_rate_limit_consume(p_bucket text, p_limit integer, p_window_seconds integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent integer;
begin
  if p_bucket is null or char_length(p_bucket) not between 1 and 128 or p_limit < 1 or p_window_seconds < 1 then
    raise exception 'invalid rate limit arguments';
  end if;

  -- Serialise attempts per bucket so concurrent requests cannot exceed the limit.
  perform pg_advisory_xact_lock(hashtext(p_bucket));

  delete from public.lead_rate_limits where created_at < now() - interval '1 day';

  select count(*) into recent
    from public.lead_rate_limits
   where bucket = p_bucket
     and created_at > now() - make_interval(secs => p_window_seconds);

  if recent >= p_limit then
    return false;
  end if;

  insert into public.lead_rate_limits (bucket) values (p_bucket);
  return true;
end;
$$;

revoke all on function public.lead_rate_limit_consume(text, integer, integer) from public, anon, authenticated;
grant execute on function public.lead_rate_limit_consume(text, integer, integer) to service_role;

-- Blog slugs: allow lowercase letters of any script (previously Latin + Hebrew only) ----------------------
alter table public.posts drop constraint posts_slug_check;
alter table public.posts add constraint posts_slug_check check (
  char_length(slug) <= 120
  and slug ~ '^[^[:space:][:upper:]/?#%&"''<>\\-]+(-[^[:space:][:upper:]/?#%&"''<>\\-]+)*$'
);

-- Consent Mode v2 default ------------------------------------------------------------------------------
alter table public.site_settings
  add column consent_default text not null default 'granted'
    constraint site_settings_consent_default_check check (consent_default in ('granted', 'denied'));

-- ═══ 20260916120000_lookup_service_area.sql ═══
-- Lookup website infrastructure — 6: service area setting.
-- Adds an admin-editable service area to the site settings. Additive only; no data is written.
-- Aborts WITHOUT changing anything if run before 1–5 or run twice.

do $$
begin
  if to_regclass('public.site_settings') is null or not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'site_settings' and column_name = 'consent_default'
  ) then
    raise exception 'Lookup service area migration aborted: apply migrations 1-5 first. Nothing was changed.';
  end if;

  if exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'site_settings' and column_name = 'service_area'
  ) then
    raise exception 'Lookup service area migration aborted: it is already applied. Nothing was changed.';
  end if;
end
$$;

alter table public.site_settings
  add column service_area text check (char_length(service_area) <= 300);

comment on column public.site_settings.service_area is
  'Visitor-facing service area (e.g. regions served). Shown on the site and used as schema.org areaServed; empty hides it.';

-- ═══ 20260917090000_lookup_consent_default_denied.sql ═══
-- Lookup website infrastructure — 7: Consent Mode defaults to "denied" for new sites.
-- Migration 5 added site_settings.consent_default with the default 'granted'. New Lookup Starter sites start
-- privacy-first: the column default becomes 'denied', and the settings row of a site that has never been configured
-- (no site name and no business name yet) is switched to 'denied'. An already configured site keeps its saved value.
-- Aborts WITHOUT changing anything if run before 1–6 or run twice.

do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'site_settings' and column_name = 'service_area'
  ) then
    raise exception 'Lookup consent default migration aborted: apply migrations 1-6 first. Nothing was changed.';
  end if;

  if exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'site_settings' and column_name = 'consent_default'
       and column_default like '%denied%'
  ) then
    raise exception 'Lookup consent default migration aborted: it is already applied. Nothing was changed.';
  end if;
end
$$;

alter table public.site_settings alter column consent_default set default 'denied';

update public.site_settings
   set consent_default = 'denied'
 where id = 1
   and site_name is null
   and business_name is null;

-- ═══ 20260918090000_lookup_post_social_seo.sql ═══
-- Lookup website infrastructure — 8: post social SEO and follow control (Lookup Starter v1.2).
-- Adds an Open Graph title/description override and a follow/nofollow flag to blog posts, matching page_seo.
-- Additive only: existing posts get NULL overrides (the existing fallbacks keep applying) and follow = true
-- (the behavior before this migration). No data is rewritten.
-- Aborts WITHOUT changing anything if run before 1–7 or run twice.

do $$
begin
  if to_regclass('public.posts') is null or not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'site_settings' and column_name = 'consent_default'
       and column_default like '%denied%'
  ) then
    raise exception 'Lookup post social SEO migration aborted: apply migrations 1-7 first. Nothing was changed.';
  end if;

  if exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'posts' and column_name = 'og_title'
  ) then
    raise exception 'Lookup post social SEO migration aborted: it is already applied. Nothing was changed.';
  end if;
end
$$;

alter table public.posts
  add column og_title text check (char_length(og_title) <= 200),
  add column og_description text check (char_length(og_description) <= 500),
  add column robots_follow boolean not null default true;

comment on column public.posts.og_title is 'Open Graph title override; empty = the resolved SEO title.';
comment on column public.posts.og_description is 'Open Graph description override; empty = the resolved meta description.';
comment on column public.posts.robots_follow is 'false = nofollow for this post (only effective while the site is indexable).';

commit;
